title: Camryn Belcher # your name (or website title) here
logo: "/images/CamrynBelcher_Headshot.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Camryn Belcher is currently a junior Computer Science major studying at Howard University. She has completed her first internship with Facebook and her second internship with Microsoft. Her intended career path is to be a Software Engineer in a front-end position. 
  <br><br>
  Her preferred programming languages: C++ (2 years), Javascript (6 months), Python (6 months). She has also worked with software such as: Repl.it (2 years), Xcode (3 months), Visual Studio (1 year), and React (3 months)
  <br><br>
  <br><br>
  <a href="https://www.linkedin.com/in/camrynbelcher/">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
